# Generated by Django 5.0 on 2023-12-22 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.region'),
        ),
    ]
